export enum Providers {
  AK = 'ak',
  ALLIANZ = 'allianz',
  ANADOLU = 'anadolu',
  ANKARA = 'ankara',
  AXA = 'axa',
  DOGA = 'doga',
  HDI = 'hdi',
  HEPIYI = 'hepiyi',
  MAGDEBURGER = 'magdeburger',
  QUICK = 'quick',
  RAY = 'ray',
  SOMPO = 'sompo',
  TURK_NIPPON = 'turk_nippon',
  TURKIYE = 'turkiye',
  TURKIYE_KATILIM = 'turkiye_katilim',
  UNICO = 'unico',
  ZURICH = 'zurich',
}
