import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';

import { Header } from '@/components/header/Header';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang={'en'} className={'scroll-smooth'}>
      <body className={`${inter.className} antialiased relative`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
